# Generated by Django 4.2.3 on 2023-07-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=20)),
                ('overall', models.CharField(max_length=200)),
                ('transport', models.CharField(max_length=200)),
                ('pickpockets', models.CharField(max_length=200)),
                ('natural', models.CharField(max_length=200)),
                ('mugging', models.CharField(max_length=200)),
                ('terrorism', models.CharField(max_length=200)),
                ('scams', models.CharField(max_length=200)),
                ('women', models.CharField(max_length=200)),
            ],
        ),
    ]
